# Generated by Django 3.0.3 on 2020-02-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('user_id', models.TextField(max_length=8000, primary_key=True, serialize=False)),
                ('offset_in_milliseconds', models.TextField()),
                ('index', models.TextField()),
                ('has_previous_playback_session', models.BooleanField(default=False)),
                ('in_playback_session', models.BooleanField(default=False)),
                ('is_playback', models.BooleanField(default=False)),
            ],
        ),
    ]
