# Generated by Django 3.0.3 on 2020-02-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbalexa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='offset_in_milliseconds',
            field=models.TextField(blank=True, null=True),
        ),
    ]
