# Generated by Django 3.0.3 on 2020-02-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbalexa', '0002_auto_20200226_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='offset_in_milliseconds',
            field=models.TextField(default=0),
        ),
    ]
